class PG_Error(Exception):
    def __init__(self):
        pass
